# Generated by Django 4.1 on 2022-09-16 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements_and_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricule', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Naissance')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements_and_modules.faculty')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements_and_modules.speciality')),
            ],
            options={
                'verbose_name': 'étudiant',
            },
        ),
    ]
