# Generated by Django 4.1 on 2022-08-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'facultée'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'note'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'spécialitée'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'étudiant'},
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(default=1, verbose_name='Coéfficient')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.faculty', verbose_name='Facultée')),
            ],
            options={
                'verbose_name': 'module',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(default=1, verbose_name='Coéfficient')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'lesson',
            },
        ),
    ]
