# Generated by Django 4.1 on 2022-08-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_faculty_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lesson'),
        ),
    ]
