# Generated by Django 4.1 on 2022-09-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems_and_levels', '0002_alter_level_options_alter_system_options'),
        ('students', '0002_student_actual_level_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='actual_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems_and_levels.level', verbose_name='Niveau actuel'),
        ),
    ]
