# Generated by Django 4.1 on 2022-10-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements_and_modules', '0004_remove_academicyear_semesters_number'),
        ('students', '0003_alter_student_actual_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements_and_modules.faculty', verbose_name='Facultée'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements_and_modules.speciality', verbose_name='Spécialitée'),
        ),
    ]
