# Generated by Django 4.1 on 2022-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_faculty_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Genre'),
        ),
    ]
