# Generated by Django 4.1 on 2022-12-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems_and_levels', '0002_alter_level_options_alter_system_options'),
        ('students', '0005_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems_and_levels.system', verbose_name='Systeme'),
        ),
    ]
