# Generated by Django 4.1 on 2022-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_result_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.semester', verbose_name='Semestre'),
        ),
    ]
