# Generated by Django 4.1 on 2022-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_mark_academic_year_semester_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year_start',
            field=models.DateField(),
        ),
    ]
