# Generated by Django 4.1 on 2022-08-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_academicyear_academic_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='coefficient',
        ),
    ]
