# Generated by Django 4.1 on 2022-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_faculty_slug_lesson_slug_module_slug_speciality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
