# Generated by Django 4.1 on 2022-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_lesson_name_alter_module_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='semesters_number',
            field=models.IntegerField(default=2),
        ),
    ]
