# Generated by Django 4.1 on 2022-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_academicyear_semesters_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='academic_year_end',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='academic_year_start',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='bigin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date début'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin'),
        ),
    ]
