# Generated by Django 4.1 on 2022-09-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_academicyear_academic_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='bigin_date',
            field=models.DateField(default=None, verbose_name='Date début'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Date fin'),
            preserve_default=False,
        ),
    ]
