# Generated by Django 4.1 on 2022-09-12 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_academicyear_bigin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='bigin_date',
            field=models.DateField(default=datetime.date(2022, 9, 12), verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 9, 12), verbose_name='Date fin'),
        ),
    ]
