# Generated by Django 4.1 on 2022-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_academicyear_bigin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(verbose_name='Date fin'),
        ),
    ]
