# Generated by Django 4.1 on 2022-09-16 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_academicyear_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='bigin_date',
            field=models.DateField(default=datetime.date(2022, 9, 16), verbose_name='Date début'),
        ),
    ]
