# Generated by Django 4.1 on 2022-09-16 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_academicyear_bigin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='bigin_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date début'),
        ),
    ]
