# Generated by Django 4.1 on 2022-09-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems_and_levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'Système'},
        ),
    ]
