# Generated by Django 4.1 on 2022-09-25 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems_and_levels', '0002_alter_level_options_alter_system_options'),
        ('departements_and_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems_and_levels.system'),
        ),
    ]
