# Generated by Django 4.1 on 2022-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements_and_modules', '0002_faculty_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_now_academic_year',
            field=models.BooleanField(blank=True, default=False, verbose_name="L'actuelle année scolaire"),
        ),
    ]
