# Generated by Django 4.1 on 2022-09-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departements_and_modules', '0003_academicyear_is_now_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='semesters_number',
        ),
    ]
