# Generated by Django 4.1 on 2022-10-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements_and_modules', '0005_module_semester_alter_module_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements_and_modules.academicyear', verbose_name='Année scolaire'),
        ),
    ]
